spring.application.name=elastic-demo
# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/product
spring.datasource.username=postgres
spring.datasource.password=Logik2021
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# Elasticsearch Configuration
spring.elasticsearch.rest.uris=http://localhost:9200
spring.elasticsearch.username=elastic 
spring.elasticsearch.password=tuWGFAUS 
